//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Habitaciones.CrearPrerreserva
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreReservaResultDto", Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class PreReservaResultDto : object
    {
        
        private string IdHoldField;
        
        private object _linksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdHold
        {
            get
            {
                return this.IdHoldField;
            }
            set
            {
                this.IdHoldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object _links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.hotelesoap.com/booking", ConfigurationName="TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap")]
    public interface CrearPreReservaWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.hotelesoap.com/booking/crearPreReservaHabitacion", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionResponse> crearPreReservaHabitacionAsync(TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPreReservaHabitacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPreReservaHabitacion", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequestBody Body;
        
        public crearPreReservaHabitacionRequest()
        {
        }
        
        public crearPreReservaHabitacionRequest(TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class crearPreReservaHabitacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idHabitacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaFin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int numeroHuespedes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> duracionHoldSegundos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> precioActual;
        
        public crearPreReservaHabitacionRequestBody()
        {
        }
        
        public crearPreReservaHabitacionRequestBody(string idHabitacion, System.DateTime fechaInicio, System.DateTime fechaFin, int numeroHuespedes, System.Nullable<int> duracionHoldSegundos, System.Nullable<decimal> precioActual)
        {
            this.idHabitacion = idHabitacion;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.numeroHuespedes = numeroHuespedes;
            this.duracionHoldSegundos = duracionHoldSegundos;
            this.precioActual = precioActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPreReservaHabitacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPreReservaHabitacionResponse", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionResponseBody Body;
        
        public crearPreReservaHabitacionResponse()
        {
        }
        
        public crearPreReservaHabitacionResponse(TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class crearPreReservaHabitacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Habitaciones.CrearPrerreserva.PreReservaResultDto crearPreReservaHabitacionResult;
        
        public crearPreReservaHabitacionResponseBody()
        {
        }
        
        public crearPreReservaHabitacionResponseBody(TravelioSOAP.Habitaciones.CrearPrerreserva.PreReservaResultDto crearPreReservaHabitacionResult)
        {
            this.crearPreReservaHabitacionResult = crearPreReservaHabitacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CrearPreReservaWSSoapChannel : TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CrearPreReservaWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap>, TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrearPreReservaWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CrearPreReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CrearPreReservaWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearPreReservaWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrearPreReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearPreReservaWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrearPreReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearPreReservaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionResponse> TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap.crearPreReservaHabitacionAsync(TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequest request)
        {
            return base.Channel.crearPreReservaHabitacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionResponse> crearPreReservaHabitacionAsync(string idHabitacion, System.DateTime fechaInicio, System.DateTime fechaFin, int numeroHuespedes, System.Nullable<int> duracionHoldSegundos, System.Nullable<decimal> precioActual)
        {
            TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequest inValue = new TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequest();
            inValue.Body = new TravelioSOAP.Habitaciones.CrearPrerreserva.crearPreReservaHabitacionRequestBody();
            inValue.Body.idHabitacion = idHabitacion;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            inValue.Body.numeroHuespedes = numeroHuespedes;
            inValue.Body.duracionHoldSegundos = duracionHoldSegundos;
            inValue.Body.precioActual = precioActual;
            return ((TravelioSOAP.Habitaciones.CrearPrerreserva.CrearPreReservaWSSoap)(this)).crearPreReservaHabitacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearPreReservaWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearPreReservaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearPreReservaWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/CrearPreReservaWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearPreReservaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/CrearPreReservaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CrearPreReservaWSSoap,
            
            CrearPreReservaWSSoap12,
        }
    }
}
