//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Mesas.Busqueda
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", ConfigurationName="TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap")]
    public interface BusBusquedaWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/BuscarMesas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Busqueda.BuscarMesasResponse1> BuscarMesasAsync(TravelioSOAP.Mesas.Busqueda.BuscarMesasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class BuscarMesasResponse
    {
        
        private BuscarMesasResult buscarMesasResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BuscarMesasResult BuscarMesasResult
        {
            get
            {
                return this.buscarMesasResultField;
            }
            set
            {
                this.buscarMesasResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class BuscarMesasResult
    {
        
        private string mensajeField;
        
        private int totalField;
        
        private MesaItem[] mesasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Mesa")]
        public MesaItem[] Mesas
        {
            get
            {
                return this.mesasField;
            }
            set
            {
                this.mesasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class MesaItem
    {
        
        private int idMesaField;
        
        private int idRestauranteField;
        
        private int numeroMesaField;
        
        private string tipoMesaField;
        
        private int capacidadField;
        
        private decimal precioField;
        
        private string imagenURLField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdMesa
        {
            get
            {
                return this.idMesaField;
            }
            set
            {
                this.idMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdRestaurante
        {
            get
            {
                return this.idRestauranteField;
            }
            set
            {
                this.idRestauranteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumeroMesa
        {
            get
            {
                return this.numeroMesaField;
            }
            set
            {
                this.numeroMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TipoMesa
        {
            get
            {
                return this.tipoMesaField;
            }
            set
            {
                this.tipoMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Capacidad
        {
            get
            {
                return this.capacidadField;
            }
            set
            {
                this.capacidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImagenURL
        {
            get
            {
                return this.imagenURLField;
            }
            set
            {
                this.imagenURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarMesas", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class BuscarMesasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> capacidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=1)]
        public string tipoMesa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=2)]
        public string estado;
        
        public BuscarMesasRequest()
        {
        }
        
        public BuscarMesasRequest(System.Nullable<int> capacidad, string tipoMesa, string estado)
        {
            this.capacidad = capacidad;
            this.tipoMesa = tipoMesa;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarMesasResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class BuscarMesasResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public TravelioSOAP.Mesas.Busqueda.BuscarMesasResponse BuscarMesasResponse;
        
        public BuscarMesasResponse1()
        {
        }
        
        public BuscarMesasResponse1(TravelioSOAP.Mesas.Busqueda.BuscarMesasResponse BuscarMesasResponse)
        {
            this.BuscarMesasResponse = BuscarMesasResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface BusBusquedaWSSoapChannel : TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BusBusquedaWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap>, TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BusBusquedaWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BusBusquedaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), BusBusquedaWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusBusquedaWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BusBusquedaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusBusquedaWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BusBusquedaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusBusquedaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Busqueda.BuscarMesasResponse1> TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap.BuscarMesasAsync(TravelioSOAP.Mesas.Busqueda.BuscarMesasRequest request)
        {
            return base.Channel.BuscarMesasAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Busqueda.BuscarMesasResponse1> BuscarMesasAsync(System.Nullable<int> capacidad, string tipoMesa, string estado)
        {
            TravelioSOAP.Mesas.Busqueda.BuscarMesasRequest inValue = new TravelioSOAP.Mesas.Busqueda.BuscarMesasRequest();
            inValue.capacidad = capacidad;
            inValue.tipoMesa = tipoMesa;
            inValue.estado = estado;
            return ((TravelioSOAP.Mesas.Busqueda.BusBusquedaWSSoap)(this)).BuscarMesasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusBusquedaWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BusBusquedaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusBusquedaWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusBusquedaWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BusBusquedaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusBusquedaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BusBusquedaWSSoap,
            
            BusBusquedaWSSoap12,
        }
    }
}
