//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Mesas.Reserva
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", ConfigurationName="TravelioSOAP.Mesas.Reserva.BusReservaWSSoap")]
    public interface BusReservaWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/CrearPreReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.CrearPreReservaResponse> CrearPreReservaAsync(TravelioSOAP.Mesas.Reserva.CrearPreReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/ConfirmarReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.ConfirmarReservaResponse1> ConfirmarReservaAsync(TravelioSOAP.Mesas.Reserva.ConfirmarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/BuscarReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.BuscarReservaResponse1> BuscarReservaAsync(TravelioSOAP.Mesas.Reserva.BuscarReservaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class PreReservaResponse
    {
        
        private int idMesaField;
        
        private string fechaReservaField;
        
        private int numeroPersonasField;
        
        private int duracionHoldSegundosField;
        
        private string idHoldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdMesa
        {
            get
            {
                return this.idMesaField;
            }
            set
            {
                this.idMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FechaReserva
        {
            get
            {
                return this.fechaReservaField;
            }
            set
            {
                this.fechaReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumeroPersonas
        {
            get
            {
                return this.numeroPersonasField;
            }
            set
            {
                this.numeroPersonasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DuracionHoldSegundos
        {
            get
            {
                return this.duracionHoldSegundosField;
            }
            set
            {
                this.duracionHoldSegundosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IdHold
        {
            get
            {
                return this.idHoldField;
            }
            set
            {
                this.idHoldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class BuscarReservaResponse
    {
        
        private string mensajeField;
        
        private int idReservaField;
        
        private int idMesaField;
        
        private System.DateTime fechaField;
        
        private int numeroPersonasField;
        
        private string estadoField;
        
        private string tipoMesaField;
        
        private string nombreClienteField;
        
        private string apellidoClienteField;
        
        private string correoField;
        
        private decimal valorPagadoField;
        
        private string uriFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdReserva
        {
            get
            {
                return this.idReservaField;
            }
            set
            {
                this.idReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdMesa
        {
            get
            {
                return this.idMesaField;
            }
            set
            {
                this.idMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NumeroPersonas
        {
            get
            {
                return this.numeroPersonasField;
            }
            set
            {
                this.numeroPersonasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TipoMesa
        {
            get
            {
                return this.tipoMesaField;
            }
            set
            {
                this.tipoMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NombreCliente
        {
            get
            {
                return this.nombreClienteField;
            }
            set
            {
                this.nombreClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ApellidoCliente
        {
            get
            {
                return this.apellidoClienteField;
            }
            set
            {
                this.apellidoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal ValorPagado
        {
            get
            {
                return this.valorPagadoField;
            }
            set
            {
                this.valorPagadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UriFactura
        {
            get
            {
                return this.uriFacturaField;
            }
            set
            {
                this.uriFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class ConfirmarReservaResponse
    {
        
        private string mensajeField;
        
        private string idReservaField;
        
        private int idMesaField;
        
        private string nombreClienteField;
        
        private string apellidoClienteField;
        
        private string correoField;
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        private string fechaReservaField;
        
        private int numeroPersonasField;
        
        private decimal valorPagadoField;
        
        private string uriFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdReserva
        {
            get
            {
                return this.idReservaField;
            }
            set
            {
                this.idReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdMesa
        {
            get
            {
                return this.idMesaField;
            }
            set
            {
                this.idMesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NombreCliente
        {
            get
            {
                return this.nombreClienteField;
            }
            set
            {
                this.nombreClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApellidoCliente
        {
            get
            {
                return this.apellidoClienteField;
            }
            set
            {
                this.apellidoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FechaReserva
        {
            get
            {
                return this.fechaReservaField;
            }
            set
            {
                this.fechaReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int NumeroPersonas
        {
            get
            {
                return this.numeroPersonasField;
            }
            set
            {
                this.numeroPersonasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal ValorPagado
        {
            get
            {
                return this.valorPagadoField;
            }
            set
            {
                this.valorPagadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UriFactura
        {
            get
            {
                return this.uriFacturaField;
            }
            set
            {
                this.uriFacturaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearPreReserva", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class CrearPreReservaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public string id_mesa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=1)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=2)]
        public int numero_clientes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> duracionHoldSegundos;
        
        public CrearPreReservaRequest()
        {
        }
        
        public CrearPreReservaRequest(string id_mesa, string fecha, int numero_clientes, System.Nullable<int> duracionHoldSegundos)
        {
            this.id_mesa = id_mesa;
            this.fecha = fecha;
            this.numero_clientes = numero_clientes;
            this.duracionHoldSegundos = duracionHoldSegundos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearPreReservaResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class CrearPreReservaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public TravelioSOAP.Mesas.Reserva.PreReservaResponse CrearPreReservaResult;
        
        public CrearPreReservaResponse()
        {
        }
        
        public CrearPreReservaResponse(TravelioSOAP.Mesas.Reserva.PreReservaResponse CrearPreReservaResult)
        {
            this.CrearPreReservaResult = CrearPreReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarReserva", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class ConfirmarReservaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public string id_mesa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=1)]
        public string id_hold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=2)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=3)]
        public string apellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=4)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=5)]
        public string tipo_identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=6)]
        public string identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=7)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=8)]
        public int personas;
        
        public ConfirmarReservaRequest()
        {
        }
        
        public ConfirmarReservaRequest(string id_mesa, string id_hold, string nombre, string apellido, string correo, string tipo_identificacion, string identificacion, string fecha, int personas)
        {
            this.id_mesa = id_mesa;
            this.id_hold = id_hold;
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.tipo_identificacion = tipo_identificacion;
            this.identificacion = identificacion;
            this.fecha = fecha;
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarReservaResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class ConfirmarReservaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TravelioSOAP.Mesas.Reserva.ConfirmarReservaResponse ConfirmarReservaResult;
        
        public ConfirmarReservaResponse1()
        {
        }
        
        public ConfirmarReservaResponse1(TravelioSOAP.Mesas.Reserva.ConfirmarReservaResponse ConfirmarReservaResult)
        {
            this.ConfirmarReservaResult = ConfirmarReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarReserva", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class BuscarReservaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public string idReserva;
        
        public BuscarReservaRequest()
        {
        }
        
        public BuscarReservaRequest(string idReserva)
        {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarReservaResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class BuscarReservaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TravelioSOAP.Mesas.Reserva.BuscarReservaResponse BuscarReservaResult;
        
        public BuscarReservaResponse1()
        {
        }
        
        public BuscarReservaResponse1(TravelioSOAP.Mesas.Reserva.BuscarReservaResponse BuscarReservaResult)
        {
            this.BuscarReservaResult = BuscarReservaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface BusReservaWSSoapChannel : TravelioSOAP.Mesas.Reserva.BusReservaWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BusReservaWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Mesas.Reserva.BusReservaWSSoap>, TravelioSOAP.Mesas.Reserva.BusReservaWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BusReservaWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BusReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), BusReservaWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusReservaWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BusReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusReservaWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BusReservaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusReservaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.CrearPreReservaResponse> TravelioSOAP.Mesas.Reserva.BusReservaWSSoap.CrearPreReservaAsync(TravelioSOAP.Mesas.Reserva.CrearPreReservaRequest request)
        {
            return base.Channel.CrearPreReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.CrearPreReservaResponse> CrearPreReservaAsync(string id_mesa, string fecha, int numero_clientes, System.Nullable<int> duracionHoldSegundos)
        {
            TravelioSOAP.Mesas.Reserva.CrearPreReservaRequest inValue = new TravelioSOAP.Mesas.Reserva.CrearPreReservaRequest();
            inValue.id_mesa = id_mesa;
            inValue.fecha = fecha;
            inValue.numero_clientes = numero_clientes;
            inValue.duracionHoldSegundos = duracionHoldSegundos;
            return ((TravelioSOAP.Mesas.Reserva.BusReservaWSSoap)(this)).CrearPreReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.ConfirmarReservaResponse1> TravelioSOAP.Mesas.Reserva.BusReservaWSSoap.ConfirmarReservaAsync(TravelioSOAP.Mesas.Reserva.ConfirmarReservaRequest request)
        {
            return base.Channel.ConfirmarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.ConfirmarReservaResponse1> ConfirmarReservaAsync(string id_mesa, string id_hold, string nombre, string apellido, string correo, string tipo_identificacion, string identificacion, string fecha, int personas)
        {
            TravelioSOAP.Mesas.Reserva.ConfirmarReservaRequest inValue = new TravelioSOAP.Mesas.Reserva.ConfirmarReservaRequest();
            inValue.id_mesa = id_mesa;
            inValue.id_hold = id_hold;
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.correo = correo;
            inValue.tipo_identificacion = tipo_identificacion;
            inValue.identificacion = identificacion;
            inValue.fecha = fecha;
            inValue.personas = personas;
            return ((TravelioSOAP.Mesas.Reserva.BusReservaWSSoap)(this)).ConfirmarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.BuscarReservaResponse1> TravelioSOAP.Mesas.Reserva.BusReservaWSSoap.BuscarReservaAsync(TravelioSOAP.Mesas.Reserva.BuscarReservaRequest request)
        {
            return base.Channel.BuscarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Reserva.BuscarReservaResponse1> BuscarReservaAsync(string idReserva)
        {
            TravelioSOAP.Mesas.Reserva.BuscarReservaRequest inValue = new TravelioSOAP.Mesas.Reserva.BuscarReservaRequest();
            inValue.idReserva = idReserva;
            return ((TravelioSOAP.Mesas.Reserva.BusReservaWSSoap)(this)).BuscarReservaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusReservaWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BusReservaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusReservaWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusReservaWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BusReservaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusReservaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BusReservaWSSoap,
            
            BusReservaWSSoap12,
        }
    }
}
