//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Facturacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaCreadaDto", Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class FacturaCreadaDto : object
    {
        
        private string IdFacturaField;
        
        private string UrlFacturaField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrlFactura
        {
            get
            {
                return this.UrlFacturaField;
            }
            set
            {
                this.UrlFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.rentaautos.com.ec/", ConfigurationName="TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap")]
    public interface WS_FacturaIntegracionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.rentaautos.com.ec/EmitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.EmitirFacturaResponse> EmitirFacturaAsync(TravelioSOAP.Autos.Facturacion.EmitirFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.rentaautos.com.ec/TestConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.TestConexionResponse> TestConexionAsync(TravelioSOAP.Autos.Facturacion.TestConexionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFactura", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Facturacion.EmitirFacturaRequestBody Body;
        
        public EmitirFacturaRequest()
        {
        }
        
        public EmitirFacturaRequest(TravelioSOAP.Autos.Facturacion.EmitirFacturaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class EmitirFacturaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_reserva;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo_identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal valor;
        
        public EmitirFacturaRequestBody()
        {
        }
        
        public EmitirFacturaRequestBody(string id_reserva, string correo, string nombre, string tipo_identificacion, string identificacion, decimal valor)
        {
            this.id_reserva = id_reserva;
            this.correo = correo;
            this.nombre = nombre;
            this.tipo_identificacion = tipo_identificacion;
            this.identificacion = identificacion;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFacturaResponse", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Facturacion.EmitirFacturaResponseBody Body;
        
        public EmitirFacturaResponse()
        {
        }
        
        public EmitirFacturaResponse(TravelioSOAP.Autos.Facturacion.EmitirFacturaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class EmitirFacturaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Facturacion.FacturaCreadaDto EmitirFacturaResult;
        
        public EmitirFacturaResponseBody()
        {
        }
        
        public EmitirFacturaResponseBody(TravelioSOAP.Autos.Facturacion.FacturaCreadaDto EmitirFacturaResult)
        {
            this.EmitirFacturaResult = EmitirFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexion", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Facturacion.TestConexionRequestBody Body;
        
        public TestConexionRequest()
        {
        }
        
        public TestConexionRequest(TravelioSOAP.Autos.Facturacion.TestConexionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConexionRequestBody
    {
        
        public TestConexionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexionResponse", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Facturacion.TestConexionResponseBody Body;
        
        public TestConexionResponse()
        {
        }
        
        public TestConexionResponse(TravelioSOAP.Autos.Facturacion.TestConexionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class TestConexionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConexionResult;
        
        public TestConexionResponseBody()
        {
        }
        
        public TestConexionResponseBody(string TestConexionResult)
        {
            this.TestConexionResult = TestConexionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_FacturaIntegracionSoapChannel : TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_FacturaIntegracionSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap>, TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_FacturaIntegracionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_FacturaIntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_FacturaIntegracionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FacturaIntegracionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_FacturaIntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FacturaIntegracionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_FacturaIntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FacturaIntegracionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.EmitirFacturaResponse> TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap.EmitirFacturaAsync(TravelioSOAP.Autos.Facturacion.EmitirFacturaRequest request)
        {
            return base.Channel.EmitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.EmitirFacturaResponse> EmitirFacturaAsync(string id_reserva, string correo, string nombre, string tipo_identificacion, string identificacion, decimal valor)
        {
            TravelioSOAP.Autos.Facturacion.EmitirFacturaRequest inValue = new TravelioSOAP.Autos.Facturacion.EmitirFacturaRequest();
            inValue.Body = new TravelioSOAP.Autos.Facturacion.EmitirFacturaRequestBody();
            inValue.Body.id_reserva = id_reserva;
            inValue.Body.correo = correo;
            inValue.Body.nombre = nombre;
            inValue.Body.tipo_identificacion = tipo_identificacion;
            inValue.Body.identificacion = identificacion;
            inValue.Body.valor = valor;
            return ((TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap)(this)).EmitirFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.TestConexionResponse> TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap.TestConexionAsync(TravelioSOAP.Autos.Facturacion.TestConexionRequest request)
        {
            return base.Channel.TestConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Facturacion.TestConexionResponse> TestConexionAsync()
        {
            TravelioSOAP.Autos.Facturacion.TestConexionRequest inValue = new TravelioSOAP.Autos.Facturacion.TestConexionRequest();
            inValue.Body = new TravelioSOAP.Autos.Facturacion.TestConexionRequestBody();
            return ((TravelioSOAP.Autos.Facturacion.WS_FacturaIntegracionSoap)(this)).TestConexionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_FacturaIntegracionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_FacturaIntegracionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_FacturaIntegracionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_FacturaIntegracion.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_FacturaIntegracionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_FacturaIntegracion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_FacturaIntegracionSoap,
            
            WS_FacturaIntegracionSoap12,
        }
    }
}
