//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Aerolinea
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://skyandes.com/integracion/")]
    public partial class Flight : object
    {
        
        private int FlightIdField;
        
        private int OriginIdField;
        
        private int DestinationIdField;
        
        private string AirlineField;
        
        private string FlightNumberField;
        
        private System.DateTime DepartureTimeField;
        
        private System.DateTime ArrivalTimeField;
        
        private string DurationField;
        
        private string CancellationPolicyField;
        
        private string CabinClassField;
        
        private int AircraftIdField;
        
        private decimal PriceField;
        
        private int SeatsAvailableField;
        
        private string OriginNameField;
        
        private string DestinationNameField;
        
        private string AircraftModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FlightId
        {
            get
            {
                return this.FlightIdField;
            }
            set
            {
                this.FlightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginId
        {
            get
            {
                return this.OriginIdField;
            }
            set
            {
                this.OriginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DestinationId
        {
            get
            {
                return this.DestinationIdField;
            }
            set
            {
                this.DestinationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Airline
        {
            get
            {
                return this.AirlineField;
            }
            set
            {
                this.AirlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FlightNumber
        {
            get
            {
                return this.FlightNumberField;
            }
            set
            {
                this.FlightNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DepartureTime
        {
            get
            {
                return this.DepartureTimeField;
            }
            set
            {
                this.DepartureTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime ArrivalTime
        {
            get
            {
                return this.ArrivalTimeField;
            }
            set
            {
                this.ArrivalTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CancellationPolicy
        {
            get
            {
                return this.CancellationPolicyField;
            }
            set
            {
                this.CancellationPolicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CabinClass
        {
            get
            {
                return this.CabinClassField;
            }
            set
            {
                this.CabinClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int AircraftId
        {
            get
            {
                return this.AircraftIdField;
            }
            set
            {
                this.AircraftIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int SeatsAvailable
        {
            get
            {
                return this.SeatsAvailableField;
            }
            set
            {
                this.SeatsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OriginName
        {
            get
            {
                return this.OriginNameField;
            }
            set
            {
                this.OriginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DestinationName
        {
            get
            {
                return this.DestinationNameField;
            }
            set
            {
                this.DestinationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string AircraftModel
        {
            get
            {
                return this.AircraftModelField;
            }
            set
            {
                this.AircraftModelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://skyandes.com/integracion/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOHoldResponse", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOHoldResponse : object
    {
        
        private int IdVueloField;
        
        private string HoldIdField;
        
        private System.DateTime ExpiraEnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVuelo
        {
            get
            {
                return this.IdVueloField;
            }
            set
            {
                this.IdVueloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoldId
        {
            get
            {
                return this.HoldIdField;
            }
            set
            {
                this.HoldIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ExpiraEn
        {
            get
            {
                return this.ExpiraEnField;
            }
            set
            {
                this.ExpiraEnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPasajero", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOPasajero : object
    {
        
        private string NombreField;
        
        private string ApellidoField;
        
        private string TipoIdentificacionField;
        
        private string IdentificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoIdentificacion
        {
            get
            {
                return this.TipoIdentificacionField;
            }
            set
            {
                this.TipoIdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOReservaResponse", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOReservaResponse : object
    {
        
        private int IdReservaField;
        
        private string CodigoReservaField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReserva
        {
            get
            {
                return this.IdReservaField;
            }
            set
            {
                this.IdReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoReserva
        {
            get
            {
                return this.CodigoReservaField;
            }
            set
            {
                this.CodigoReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOFacturaRequest", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOFacturaRequest : object
    {
        
        private int ReservaIdField;
        
        private decimal SubtotalField;
        
        private decimal IvaField;
        
        private decimal TotalField;
        
        private TravelioSOAP.Aerolinea.DTOClienteFactura ClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReservaId
        {
            get
            {
                return this.ReservaIdField;
            }
            set
            {
                this.ReservaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Iva
        {
            get
            {
                return this.IvaField;
            }
            set
            {
                this.IvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public TravelioSOAP.Aerolinea.DTOClienteFactura Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOClienteFactura", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOClienteFactura : object
    {
        
        private string NombreField;
        
        private string DocumentoField;
        
        private string CorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Documento
        {
            get
            {
                return this.DocumentoField;
            }
            set
            {
                this.DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOFacturaResponse", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOFacturaResponse : object
    {
        
        private string UriFacturaField;
        
        private bool PagadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UriFactura
        {
            get
            {
                return this.UriFacturaField;
            }
            set
            {
                this.UriFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool Pagado
        {
            get
            {
                return this.PagadoField;
            }
            set
            {
                this.PagadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUsuarioExterno", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOUsuarioExterno : object
    {
        
        private string NombreField;
        
        private string ApellidoField;
        
        private string CorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUsuarioExternoResponse", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOUsuarioExternoResponse : object
    {
        
        private int IdUsuarioField;
        
        private string NombreCompletoField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOBuscarReservaResponse", Namespace="http://skyandes.com/integracion/")]
    public partial class DTOBuscarReservaResponse : object
    {
        
        private int IdReservaField;
        
        private string AerolineaField;
        
        private string OrigenField;
        
        private string DestinoField;
        
        private string TipoCabinaField;
        
        private System.DateTime FechaField;
        
        private TravelioSOAP.Aerolinea.DTOPasajero[] PasajerosField;
        
        private int AsientosReservadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReserva
        {
            get
            {
                return this.IdReservaField;
            }
            set
            {
                this.IdReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Aerolinea
        {
            get
            {
                return this.AerolineaField;
            }
            set
            {
                this.AerolineaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Origen
        {
            get
            {
                return this.OrigenField;
            }
            set
            {
                this.OrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Destino
        {
            get
            {
                return this.DestinoField;
            }
            set
            {
                this.DestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TipoCabina
        {
            get
            {
                return this.TipoCabinaField;
            }
            set
            {
                this.TipoCabinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public TravelioSOAP.Aerolinea.DTOPasajero[] Pasajeros
        {
            get
            {
                return this.PasajerosField;
            }
            set
            {
                this.PasajerosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AsientosReservados
        {
            get
            {
                return this.AsientosReservadosField;
            }
            set
            {
                this.AsientosReservadosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://skyandes.com/integracion/", ConfigurationName="TravelioSOAP.Aerolinea.WS_IntegracionSoap")]
    public interface WS_IntegracionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/buscarVuelos", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> buscarVuelosAsync(TravelioSOAP.Aerolinea.buscarVuelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/validarDisponibilidadVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validarDisponibilidadVueloAsync(int flightId, int passengers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/crearPreReservaVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearPreReservaVueloResponse> crearPreReservaVueloAsync(TravelioSOAP.Aerolinea.crearPreReservaVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/reservarVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.reservarVueloResponse> reservarVueloAsync(TravelioSOAP.Aerolinea.reservarVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/emitirFacturaVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.emitirFacturaVueloResponse> emitirFacturaVueloAsync(TravelioSOAP.Aerolinea.emitirFacturaVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/crearUsuarioExterno", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearUsuarioExternoResponse> crearUsuarioExternoAsync(TravelioSOAP.Aerolinea.crearUsuarioExternoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://skyandes.com/integracion/buscarDatosReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarDatosReservaResponse> buscarDatosReservaAsync(TravelioSOAP.Aerolinea.buscarDatosReservaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarVuelosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarVuelos", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.buscarVuelosRequestBody Body;
        
        public buscarVuelosRequest()
        {
        }
        
        public buscarVuelosRequest(TravelioSOAP.Aerolinea.buscarVuelosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class buscarVuelosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string origin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cabin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> passengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> priceMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> priceMax;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string currency;
        
        public buscarVuelosRequestBody()
        {
        }
        
        public buscarVuelosRequestBody(string origin, string destination, System.Nullable<System.DateTime> dateFrom, string cabin, System.Nullable<int> passengers, System.Nullable<decimal> priceMin, System.Nullable<decimal> priceMax, string currency)
        {
            this.origin = origin;
            this.destination = destination;
            this.dateFrom = dateFrom;
            this.cabin = cabin;
            this.passengers = passengers;
            this.priceMin = priceMin;
            this.priceMax = priceMax;
            this.currency = currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarVuelosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarVuelosResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.buscarVuelosResponseBody Body;
        
        public buscarVuelosResponse()
        {
        }
        
        public buscarVuelosResponse(TravelioSOAP.Aerolinea.buscarVuelosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class buscarVuelosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.Flight[] buscarVuelosResult;
        
        public buscarVuelosResponseBody()
        {
        }
        
        public buscarVuelosResponseBody(TravelioSOAP.Aerolinea.Flight[] buscarVuelosResult)
        {
            this.buscarVuelosResult = buscarVuelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPreReservaVueloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPreReservaVuelo", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.crearPreReservaVueloRequestBody Body;
        
        public crearPreReservaVueloRequest()
        {
        }
        
        public crearPreReservaVueloRequest(TravelioSOAP.Aerolinea.crearPreReservaVueloRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class crearPreReservaVueloRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int flightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TravelioSOAP.Aerolinea.ArrayOfString seatNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int holdDurationSeconds;
        
        public crearPreReservaVueloRequestBody()
        {
        }
        
        public crearPreReservaVueloRequestBody(int flightId, TravelioSOAP.Aerolinea.ArrayOfString seatNumbers, int holdDurationSeconds)
        {
            this.flightId = flightId;
            this.seatNumbers = seatNumbers;
            this.holdDurationSeconds = holdDurationSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPreReservaVueloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPreReservaVueloResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.crearPreReservaVueloResponseBody Body;
        
        public crearPreReservaVueloResponse()
        {
        }
        
        public crearPreReservaVueloResponse(TravelioSOAP.Aerolinea.crearPreReservaVueloResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class crearPreReservaVueloResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOHoldResponse crearPreReservaVueloResult;
        
        public crearPreReservaVueloResponseBody()
        {
        }
        
        public crearPreReservaVueloResponseBody(TravelioSOAP.Aerolinea.DTOHoldResponse crearPreReservaVueloResult)
        {
            this.crearPreReservaVueloResult = crearPreReservaVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservarVueloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservarVuelo", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.reservarVueloRequestBody Body;
        
        public reservarVueloRequest()
        {
        }
        
        public reservarVueloRequest(TravelioSOAP.Aerolinea.reservarVueloRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class reservarVueloRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int flightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string holdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TravelioSOAP.Aerolinea.DTOPasajero[] passengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        public reservarVueloRequestBody()
        {
        }
        
        public reservarVueloRequestBody(int flightId, string holdId, TravelioSOAP.Aerolinea.DTOPasajero[] passengers, string email)
        {
            this.flightId = flightId;
            this.holdId = holdId;
            this.passengers = passengers;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservarVueloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservarVueloResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.reservarVueloResponseBody Body;
        
        public reservarVueloResponse()
        {
        }
        
        public reservarVueloResponse(TravelioSOAP.Aerolinea.reservarVueloResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class reservarVueloResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOReservaResponse reservarVueloResult;
        
        public reservarVueloResponseBody()
        {
        }
        
        public reservarVueloResponseBody(TravelioSOAP.Aerolinea.DTOReservaResponse reservarVueloResult)
        {
            this.reservarVueloResult = reservarVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emitirFacturaVueloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emitirFacturaVuelo", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.emitirFacturaVueloRequestBody Body;
        
        public emitirFacturaVueloRequest()
        {
        }
        
        public emitirFacturaVueloRequest(TravelioSOAP.Aerolinea.emitirFacturaVueloRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class emitirFacturaVueloRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOFacturaRequest request;
        
        public emitirFacturaVueloRequestBody()
        {
        }
        
        public emitirFacturaVueloRequestBody(TravelioSOAP.Aerolinea.DTOFacturaRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emitirFacturaVueloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emitirFacturaVueloResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.emitirFacturaVueloResponseBody Body;
        
        public emitirFacturaVueloResponse()
        {
        }
        
        public emitirFacturaVueloResponse(TravelioSOAP.Aerolinea.emitirFacturaVueloResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class emitirFacturaVueloResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOFacturaResponse emitirFacturaVueloResult;
        
        public emitirFacturaVueloResponseBody()
        {
        }
        
        public emitirFacturaVueloResponseBody(TravelioSOAP.Aerolinea.DTOFacturaResponse emitirFacturaVueloResult)
        {
            this.emitirFacturaVueloResult = emitirFacturaVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearUsuarioExternoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearUsuarioExterno", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.crearUsuarioExternoRequestBody Body;
        
        public crearUsuarioExternoRequest()
        {
        }
        
        public crearUsuarioExternoRequest(TravelioSOAP.Aerolinea.crearUsuarioExternoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class crearUsuarioExternoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOUsuarioExterno usuario;
        
        public crearUsuarioExternoRequestBody()
        {
        }
        
        public crearUsuarioExternoRequestBody(TravelioSOAP.Aerolinea.DTOUsuarioExterno usuario)
        {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearUsuarioExternoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearUsuarioExternoResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.crearUsuarioExternoResponseBody Body;
        
        public crearUsuarioExternoResponse()
        {
        }
        
        public crearUsuarioExternoResponse(TravelioSOAP.Aerolinea.crearUsuarioExternoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class crearUsuarioExternoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOUsuarioExternoResponse crearUsuarioExternoResult;
        
        public crearUsuarioExternoResponseBody()
        {
        }
        
        public crearUsuarioExternoResponseBody(TravelioSOAP.Aerolinea.DTOUsuarioExternoResponse crearUsuarioExternoResult)
        {
            this.crearUsuarioExternoResult = crearUsuarioExternoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarDatosReservaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarDatosReserva", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.buscarDatosReservaRequestBody Body;
        
        public buscarDatosReservaRequest()
        {
        }
        
        public buscarDatosReservaRequest(TravelioSOAP.Aerolinea.buscarDatosReservaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class buscarDatosReservaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int reservationId;
        
        public buscarDatosReservaRequestBody()
        {
        }
        
        public buscarDatosReservaRequestBody(int reservationId)
        {
            this.reservationId = reservationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarDatosReservaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarDatosReservaResponse", Namespace="http://skyandes.com/integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.buscarDatosReservaResponseBody Body;
        
        public buscarDatosReservaResponse()
        {
        }
        
        public buscarDatosReservaResponse(TravelioSOAP.Aerolinea.buscarDatosReservaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://skyandes.com/integracion/")]
    public partial class buscarDatosReservaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Aerolinea.DTOBuscarReservaResponse buscarDatosReservaResult;
        
        public buscarDatosReservaResponseBody()
        {
        }
        
        public buscarDatosReservaResponseBody(TravelioSOAP.Aerolinea.DTOBuscarReservaResponse buscarDatosReservaResult)
        {
            this.buscarDatosReservaResult = buscarDatosReservaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_IntegracionSoapChannel : TravelioSOAP.Aerolinea.WS_IntegracionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_IntegracionSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Aerolinea.WS_IntegracionSoap>, TravelioSOAP.Aerolinea.WS_IntegracionSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_IntegracionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_IntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_IntegracionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_IntegracionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_IntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_IntegracionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_IntegracionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_IntegracionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.buscarVuelosAsync(TravelioSOAP.Aerolinea.buscarVuelosRequest request)
        {
            return base.Channel.buscarVuelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> buscarVuelosAsync(string origin, string destination, System.Nullable<System.DateTime> dateFrom, string cabin, System.Nullable<int> passengers, System.Nullable<decimal> priceMin, System.Nullable<decimal> priceMax, string currency)
        {
            TravelioSOAP.Aerolinea.buscarVuelosRequest inValue = new TravelioSOAP.Aerolinea.buscarVuelosRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.buscarVuelosRequestBody();
            inValue.Body.origin = origin;
            inValue.Body.destination = destination;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.cabin = cabin;
            inValue.Body.passengers = passengers;
            inValue.Body.priceMin = priceMin;
            inValue.Body.priceMax = priceMax;
            inValue.Body.currency = currency;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).buscarVuelosAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> validarDisponibilidadVueloAsync(int flightId, int passengers)
        {
            return base.Channel.validarDisponibilidadVueloAsync(flightId, passengers);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearPreReservaVueloResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.crearPreReservaVueloAsync(TravelioSOAP.Aerolinea.crearPreReservaVueloRequest request)
        {
            return base.Channel.crearPreReservaVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearPreReservaVueloResponse> crearPreReservaVueloAsync(int flightId, TravelioSOAP.Aerolinea.ArrayOfString seatNumbers, int holdDurationSeconds)
        {
            TravelioSOAP.Aerolinea.crearPreReservaVueloRequest inValue = new TravelioSOAP.Aerolinea.crearPreReservaVueloRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.crearPreReservaVueloRequestBody();
            inValue.Body.flightId = flightId;
            inValue.Body.seatNumbers = seatNumbers;
            inValue.Body.holdDurationSeconds = holdDurationSeconds;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).crearPreReservaVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.reservarVueloResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.reservarVueloAsync(TravelioSOAP.Aerolinea.reservarVueloRequest request)
        {
            return base.Channel.reservarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.reservarVueloResponse> reservarVueloAsync(int flightId, string holdId, TravelioSOAP.Aerolinea.DTOPasajero[] passengers, string email)
        {
            TravelioSOAP.Aerolinea.reservarVueloRequest inValue = new TravelioSOAP.Aerolinea.reservarVueloRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.reservarVueloRequestBody();
            inValue.Body.flightId = flightId;
            inValue.Body.holdId = holdId;
            inValue.Body.passengers = passengers;
            inValue.Body.email = email;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).reservarVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.emitirFacturaVueloResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.emitirFacturaVueloAsync(TravelioSOAP.Aerolinea.emitirFacturaVueloRequest request)
        {
            return base.Channel.emitirFacturaVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.emitirFacturaVueloResponse> emitirFacturaVueloAsync(TravelioSOAP.Aerolinea.DTOFacturaRequest request)
        {
            TravelioSOAP.Aerolinea.emitirFacturaVueloRequest inValue = new TravelioSOAP.Aerolinea.emitirFacturaVueloRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.emitirFacturaVueloRequestBody();
            inValue.Body.request = request;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).emitirFacturaVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearUsuarioExternoResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.crearUsuarioExternoAsync(TravelioSOAP.Aerolinea.crearUsuarioExternoRequest request)
        {
            return base.Channel.crearUsuarioExternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.crearUsuarioExternoResponse> crearUsuarioExternoAsync(TravelioSOAP.Aerolinea.DTOUsuarioExterno usuario)
        {
            TravelioSOAP.Aerolinea.crearUsuarioExternoRequest inValue = new TravelioSOAP.Aerolinea.crearUsuarioExternoRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.crearUsuarioExternoRequestBody();
            inValue.Body.usuario = usuario;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).crearUsuarioExternoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarDatosReservaResponse> TravelioSOAP.Aerolinea.WS_IntegracionSoap.buscarDatosReservaAsync(TravelioSOAP.Aerolinea.buscarDatosReservaRequest request)
        {
            return base.Channel.buscarDatosReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarDatosReservaResponse> buscarDatosReservaAsync(int reservationId)
        {
            TravelioSOAP.Aerolinea.buscarDatosReservaRequest inValue = new TravelioSOAP.Aerolinea.buscarDatosReservaRequest();
            inValue.Body = new TravelioSOAP.Aerolinea.buscarDatosReservaRequestBody();
            inValue.Body.reservationId = reservationId;
            return ((TravelioSOAP.Aerolinea.WS_IntegracionSoap)(this)).buscarDatosReservaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_IntegracionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_IntegracionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_IntegracionSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://skyandesintegracion.runasp.net/WS_Integracion.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_IntegracionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://skyandesintegracion.runasp.net/WS_Integracion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_IntegracionSoap,
            
            WS_IntegracionSoap12,
        }
    }
}
