//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Aerolinea
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://withfly.aerolinea.integracion/", ConfigurationName="TravelioSOAP.Aerolinea.IntegracionServiceSoap")]
    public interface IntegracionServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/buscarVuelos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> buscarVuelosAsync(TravelioSOAP.Aerolinea.buscarVuelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/validarDisponibilidadVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> validarDisponibilidadVueloAsync(string idVuelo, int pasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/validarDisponibilidadVueloDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.ValidarDisponibilidadResponseDTO> validarDisponibilidadVueloDetalleAsync(string idVuelo, int pasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/crearPreReservaVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> crearPreReservaVueloAsync(string idVuelo, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, int duracionHoldSegundos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/crearPreReservaVueloDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.PreReservaResponseDTO> crearPreReservaVueloDetalleAsync(string idVuelo, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, int duracionHoldSegundos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/reservarVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> reservarVueloAsync(string idVuelo, string idHold, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/reservarVueloDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.ReservaResponseDTO_Integracion> reservarVueloDetalleAsync(string idVuelo, string idHold, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/emitirFacturaVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> emitirFacturaVueloAsync(string idReserva, decimal subtotal, decimal iva, decimal total, TravelioSOAP.Aerolinea.ClienteFacturaDTO cliente, string idTransaccionBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/emitirFacturaVueloDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.FacturaResponseDTO_Integracion> emitirFacturaVueloDetalleAsync(string idReserva, decimal subtotal, decimal iva, decimal total, TravelioSOAP.Aerolinea.ClienteFacturaDTO cliente, string idTransaccionBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/crearUsuarioExterno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> crearUsuarioExternoAsync(string correo, string nombre, string apellido, System.DateTime fechaNacimiento, string tipoIdentificacion, string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/crearUsuarioExternoDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.UsuarioExternoResponseDTO> crearUsuarioExternoDetalleAsync(string correo, string nombre, string apellido, System.DateTime fechaNacimiento, string tipoIdentificacion, string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/buscarDatosReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.DatosReservaDTO_Integracion> buscarDatosReservaAsync(string idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://withfly.aerolinea.integracion/TestConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class VueloDTO_Integracion
    {
        
        private string idVueloField;
        
        private string origenField;
        
        private string destinoField;
        
        private System.DateTime fechaField;
        
        private string tipoCabinaField;
        
        private int capacidadPasajerosField;
        
        private string nombreAerolineaField;
        
        private int capacidadActualField;
        
        private decimal precioNormalField;
        
        private decimal precioActualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdVuelo
        {
            get
            {
                return this.idVueloField;
            }
            set
            {
                this.idVueloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoCabina
        {
            get
            {
                return this.tipoCabinaField;
            }
            set
            {
                this.tipoCabinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CapacidadPasajeros
        {
            get
            {
                return this.capacidadPasajerosField;
            }
            set
            {
                this.capacidadPasajerosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NombreAerolinea
        {
            get
            {
                return this.nombreAerolineaField;
            }
            set
            {
                this.nombreAerolineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CapacidadActual
        {
            get
            {
                return this.capacidadActualField;
            }
            set
            {
                this.capacidadActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal PrecioNormal
        {
            get
            {
                return this.precioNormalField;
            }
            set
            {
                this.precioNormalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal PrecioActual
        {
            get
            {
                return this.precioActualField;
            }
            set
            {
                this.precioActualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class DatosReservaDTO_Integracion
    {
        
        private string idReservaField;
        
        private string origenField;
        
        private string destinoField;
        
        private string correoField;
        
        private System.DateTime fechaField;
        
        private string tipoCabinaField;
        
        private PasajeroDTO_Integracion[] pasajerosField;
        
        private string nombreAerolineaField;
        
        private int asientosReservadosField;
        
        private decimal valorPagadoField;
        
        private string uriFacturaField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdReserva
        {
            get
            {
                return this.idReservaField;
            }
            set
            {
                this.idReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoCabina
        {
            get
            {
                return this.tipoCabinaField;
            }
            set
            {
                this.tipoCabinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public PasajeroDTO_Integracion[] Pasajeros
        {
            get
            {
                return this.pasajerosField;
            }
            set
            {
                this.pasajerosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NombreAerolinea
        {
            get
            {
                return this.nombreAerolineaField;
            }
            set
            {
                this.nombreAerolineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int AsientosReservados
        {
            get
            {
                return this.asientosReservadosField;
            }
            set
            {
                this.asientosReservadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal ValorPagado
        {
            get
            {
                return this.valorPagadoField;
            }
            set
            {
                this.valorPagadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UriFactura
        {
            get
            {
                return this.uriFacturaField;
            }
            set
            {
                this.uriFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class PasajeroDTO_Integracion
    {
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaNacimientoField;
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class UsuarioExternoResponseDTO
    {
        
        private bool successField;
        
        private string messageField;
        
        private string idUsuarioField;
        
        private bool usuarioExistenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool UsuarioExistente
        {
            get
            {
                return this.usuarioExistenteField;
            }
            set
            {
                this.usuarioExistenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class FacturaResponseDTO_Integracion
    {
        
        private bool successField;
        
        private string messageField;
        
        private string uriFacturaField;
        
        private string numeroFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UriFactura
        {
            get
            {
                return this.uriFacturaField;
            }
            set
            {
                this.uriFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumeroFactura
        {
            get
            {
                return this.numeroFacturaField;
            }
            set
            {
                this.numeroFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class ClienteFacturaDTO
    {
        
        private string nombreField;
        
        private string documentoField;
        
        private string tipoDocumentoField;
        
        private string correoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class ReservaResponseDTO_Integracion
    {
        
        private bool successField;
        
        private string messageField;
        
        private string idReservaField;
        
        private string codigoReservaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdReserva
        {
            get
            {
                return this.idReservaField;
            }
            set
            {
                this.idReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CodigoReserva
        {
            get
            {
                return this.codigoReservaField;
            }
            set
            {
                this.codigoReservaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class PreReservaResponseDTO
    {
        
        private bool successField;
        
        private string messageField;
        
        private string idHoldField;
        
        private System.DateTime expiresAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdHold
        {
            get
            {
                return this.idHoldField;
            }
            set
            {
                this.idHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ExpiresAt
        {
            get
            {
                return this.expiresAtField;
            }
            set
            {
                this.expiresAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://withfly.aerolinea.integracion/")]
    public partial class ValidarDisponibilidadResponseDTO
    {
        
        private bool disponibleField;
        
        private string messageField;
        
        private int asientosDisponiblesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Disponible
        {
            get
            {
                return this.disponibleField;
            }
            set
            {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int AsientosDisponibles
        {
            get
            {
                return this.asientosDisponiblesField;
            }
            set
            {
                this.asientosDisponiblesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarVuelos", WrapperNamespace="http://withfly.aerolinea.integracion/", IsWrapped=true)]
    public partial class buscarVuelosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=0)]
        public string origen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=1)]
        public string destino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaDespegue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaLlegada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=4)]
        public string tipoCabina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pasajeros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> precioMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> precioMax;
        
        public buscarVuelosRequest()
        {
        }
        
        public buscarVuelosRequest(string origen, string destino, System.Nullable<System.DateTime> fechaDespegue, System.Nullable<System.DateTime> fechaLlegada, string tipoCabina, System.Nullable<int> pasajeros, System.Nullable<decimal> precioMin, System.Nullable<decimal> precioMax)
        {
            this.origen = origen;
            this.destino = destino;
            this.fechaDespegue = fechaDespegue;
            this.fechaLlegada = fechaLlegada;
            this.tipoCabina = tipoCabina;
            this.pasajeros = pasajeros;
            this.precioMin = precioMin;
            this.precioMax = precioMax;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarVuelosResponse", WrapperNamespace="http://withfly.aerolinea.integracion/", IsWrapped=true)]
    public partial class buscarVuelosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://withfly.aerolinea.integracion/", Order=0)]
        public TravelioSOAP.Aerolinea.VueloDTO_Integracion[] buscarVuelosResult;
        
        public buscarVuelosResponse()
        {
        }
        
        public buscarVuelosResponse(TravelioSOAP.Aerolinea.VueloDTO_Integracion[] buscarVuelosResult)
        {
            this.buscarVuelosResult = buscarVuelosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IntegracionServiceSoapChannel : TravelioSOAP.Aerolinea.IntegracionServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class IntegracionServiceSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Aerolinea.IntegracionServiceSoap>, TravelioSOAP.Aerolinea.IntegracionServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IntegracionServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(IntegracionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), IntegracionServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegracionServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IntegracionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegracionServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IntegracionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegracionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> TravelioSOAP.Aerolinea.IntegracionServiceSoap.buscarVuelosAsync(TravelioSOAP.Aerolinea.buscarVuelosRequest request)
        {
            return base.Channel.buscarVuelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.buscarVuelosResponse> buscarVuelosAsync(string origen, string destino, System.Nullable<System.DateTime> fechaDespegue, System.Nullable<System.DateTime> fechaLlegada, string tipoCabina, System.Nullable<int> pasajeros, System.Nullable<decimal> precioMin, System.Nullable<decimal> precioMax)
        {
            TravelioSOAP.Aerolinea.buscarVuelosRequest inValue = new TravelioSOAP.Aerolinea.buscarVuelosRequest();
            inValue.origen = origen;
            inValue.destino = destino;
            inValue.fechaDespegue = fechaDespegue;
            inValue.fechaLlegada = fechaLlegada;
            inValue.tipoCabina = tipoCabina;
            inValue.pasajeros = pasajeros;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            return ((TravelioSOAP.Aerolinea.IntegracionServiceSoap)(this)).buscarVuelosAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> validarDisponibilidadVueloAsync(string idVuelo, int pasajeros)
        {
            return base.Channel.validarDisponibilidadVueloAsync(idVuelo, pasajeros);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.ValidarDisponibilidadResponseDTO> validarDisponibilidadVueloDetalleAsync(string idVuelo, int pasajeros)
        {
            return base.Channel.validarDisponibilidadVueloDetalleAsync(idVuelo, pasajeros);
        }
        
        public System.Threading.Tasks.Task<string> crearPreReservaVueloAsync(string idVuelo, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, int duracionHoldSegundos)
        {
            return base.Channel.crearPreReservaVueloAsync(idVuelo, pasajeros, duracionHoldSegundos);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.PreReservaResponseDTO> crearPreReservaVueloDetalleAsync(string idVuelo, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, int duracionHoldSegundos)
        {
            return base.Channel.crearPreReservaVueloDetalleAsync(idVuelo, pasajeros, duracionHoldSegundos);
        }
        
        public System.Threading.Tasks.Task<string> reservarVueloAsync(string idVuelo, string idHold, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, string correo)
        {
            return base.Channel.reservarVueloAsync(idVuelo, idHold, pasajeros, correo);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.ReservaResponseDTO_Integracion> reservarVueloDetalleAsync(string idVuelo, string idHold, TravelioSOAP.Aerolinea.PasajeroDTO_Integracion[] pasajeros, string correo)
        {
            return base.Channel.reservarVueloDetalleAsync(idVuelo, idHold, pasajeros, correo);
        }
        
        public System.Threading.Tasks.Task<string> emitirFacturaVueloAsync(string idReserva, decimal subtotal, decimal iva, decimal total, TravelioSOAP.Aerolinea.ClienteFacturaDTO cliente, string idTransaccionBanco)
        {
            return base.Channel.emitirFacturaVueloAsync(idReserva, subtotal, iva, total, cliente, idTransaccionBanco);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.FacturaResponseDTO_Integracion> emitirFacturaVueloDetalleAsync(string idReserva, decimal subtotal, decimal iva, decimal total, TravelioSOAP.Aerolinea.ClienteFacturaDTO cliente, string idTransaccionBanco)
        {
            return base.Channel.emitirFacturaVueloDetalleAsync(idReserva, subtotal, iva, total, cliente, idTransaccionBanco);
        }
        
        public System.Threading.Tasks.Task<string> crearUsuarioExternoAsync(string correo, string nombre, string apellido, System.DateTime fechaNacimiento, string tipoIdentificacion, string identificacion)
        {
            return base.Channel.crearUsuarioExternoAsync(correo, nombre, apellido, fechaNacimiento, tipoIdentificacion, identificacion);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.UsuarioExternoResponseDTO> crearUsuarioExternoDetalleAsync(string correo, string nombre, string apellido, System.DateTime fechaNacimiento, string tipoIdentificacion, string identificacion)
        {
            return base.Channel.crearUsuarioExternoDetalleAsync(correo, nombre, apellido, fechaNacimiento, tipoIdentificacion, identificacion);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Aerolinea.DatosReservaDTO_Integracion> buscarDatosReservaAsync(string idReserva)
        {
            return base.Channel.buscarDatosReservaAsync(idReserva);
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync()
        {
            return base.Channel.TestConnectionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegracionServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.IntegracionServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegracionServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://withflysoaint.runasp.net/IntegracionService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.IntegracionServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://withflysoaint.runasp.net/IntegracionService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            IntegracionServiceSoap,
            
            IntegracionServiceSoap12,
        }
    }
}
