//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Mesas.Disponibilidad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarDisponibilidadResponse", Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class ValidarDisponibilidadResponse : object
    {
        
        private TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadResult ValidarDisponibilidadResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadResult ValidarDisponibilidadResult
        {
            get
            {
                return this.ValidarDisponibilidadResultField;
            }
            set
            {
                this.ValidarDisponibilidadResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarDisponibilidadResult", Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class ValidarDisponibilidadResult : object
    {
        
        private int IdMesaField;
        
        private System.DateTime FechaField;
        
        private bool DisponibleField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdMesa
        {
            get
            {
                return this.IdMesaField;
            }
            set
            {
                this.IdMesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Disponible
        {
            get
            {
                return this.DisponibleField;
            }
            set
            {
                this.DisponibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", ConfigurationName="TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap")]
    public interface BusDisponibilidadWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/ValidarDisponibilidadMesa", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaResponse> ValidarDisponibilidadMesaAsync(TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarDisponibilidadMesaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarDisponibilidadMesa", Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequestBody Body;
        
        public ValidarDisponibilidadMesaRequest()
        {
        }
        
        public ValidarDisponibilidadMesaRequest(TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class ValidarDisponibilidadMesaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_mesa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numeroPersonas;
        
        public ValidarDisponibilidadMesaRequestBody()
        {
        }
        
        public ValidarDisponibilidadMesaRequestBody(int id_mesa, string fecha, int numeroPersonas)
        {
            this.id_mesa = id_mesa;
            this.fecha = fecha;
            this.numeroPersonas = numeroPersonas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarDisponibilidadMesaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarDisponibilidadMesaResponse", Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaResponseBody Body;
        
        public ValidarDisponibilidadMesaResponse()
        {
        }
        
        public ValidarDisponibilidadMesaResponse(TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class ValidarDisponibilidadMesaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadResponse ValidarDisponibilidadMesaResponse;
        
        public ValidarDisponibilidadMesaResponseBody()
        {
        }
        
        public ValidarDisponibilidadMesaResponseBody(TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadResponse ValidarDisponibilidadMesaResponse)
        {
            this.ValidarDisponibilidadMesaResponse = ValidarDisponibilidadMesaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface BusDisponibilidadWSSoapChannel : TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BusDisponibilidadWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap>, TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BusDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BusDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), BusDisponibilidadWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BusDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BusDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusDisponibilidadWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaResponse> TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap.ValidarDisponibilidadMesaAsync(TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequest request)
        {
            return base.Channel.ValidarDisponibilidadMesaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaResponse> ValidarDisponibilidadMesaAsync(int id_mesa, string fecha, int numeroPersonas)
        {
            TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequest inValue = new TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequest();
            inValue.Body = new TravelioSOAP.Mesas.Disponibilidad.ValidarDisponibilidadMesaRequestBody();
            inValue.Body.id_mesa = id_mesa;
            inValue.Body.fecha = fecha;
            inValue.Body.numeroPersonas = numeroPersonas;
            return ((TravelioSOAP.Mesas.Disponibilidad.BusDisponibilidadWSSoap)(this)).ValidarDisponibilidadMesaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusDisponibilidadWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BusDisponibilidadWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusDisponibilidadWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusDisponibilidadWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BusDisponibilidadWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusDisponibilidadWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BusDisponibilidadWSSoap,
            
            BusDisponibilidadWSSoap12,
        }
    }
}
