//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Habitaciones.CrearUsuarioExterno
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioExternoDto", Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class UsuarioExternoDto : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string ApellidoField;
        
        private string DocumentoField;
        
        private string CorreoField;
        
        private string TipoDocumentoField;
        
        private bool EstadoField;
        
        private System.DateTime FechaModificacionField;
        
        private object _linksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Documento
        {
            get
            {
                return this.DocumentoField;
            }
            set
            {
                this.DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaModificacion
        {
            get
            {
                return this.FechaModificacionField;
            }
            set
            {
                this.FechaModificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public object _links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.hotelesoap.com/booking", ConfigurationName="TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap")]
    public interface CrearUsuarioExternoWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.hotelesoap.com/booking/crearUsuarioExterno", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoResponse> crearUsuarioExternoAsync(TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearUsuarioExternoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearUsuarioExterno", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequestBody Body;
        
        public crearUsuarioExternoRequest()
        {
        }
        
        public crearUsuarioExternoRequest(TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class crearUsuarioExternoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookingUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        public crearUsuarioExternoRequestBody()
        {
        }
        
        public crearUsuarioExternoRequestBody(string bookingUserId, string nombre, string apellido)
        {
            this.bookingUserId = bookingUserId;
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearUsuarioExternoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearUsuarioExternoResponse", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoResponseBody Body;
        
        public crearUsuarioExternoResponse()
        {
        }
        
        public crearUsuarioExternoResponse(TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class crearUsuarioExternoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Habitaciones.CrearUsuarioExterno.UsuarioExternoDto crearUsuarioExternoResult;
        
        public crearUsuarioExternoResponseBody()
        {
        }
        
        public crearUsuarioExternoResponseBody(TravelioSOAP.Habitaciones.CrearUsuarioExterno.UsuarioExternoDto crearUsuarioExternoResult)
        {
            this.crearUsuarioExternoResult = crearUsuarioExternoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CrearUsuarioExternoWSSoapChannel : TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CrearUsuarioExternoWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap>, TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrearUsuarioExternoWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CrearUsuarioExternoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CrearUsuarioExternoWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearUsuarioExternoWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrearUsuarioExternoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearUsuarioExternoWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrearUsuarioExternoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearUsuarioExternoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoResponse> TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap.crearUsuarioExternoAsync(TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequest request)
        {
            return base.Channel.crearUsuarioExternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoResponse> crearUsuarioExternoAsync(string bookingUserId, string nombre, string apellido)
        {
            TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequest inValue = new TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequest();
            inValue.Body = new TravelioSOAP.Habitaciones.CrearUsuarioExterno.crearUsuarioExternoRequestBody();
            inValue.Body.bookingUserId = bookingUserId;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            return ((TravelioSOAP.Habitaciones.CrearUsuarioExterno.CrearUsuarioExternoWSSoap)(this)).crearUsuarioExternoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearUsuarioExternoWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearUsuarioExternoWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearUsuarioExternoWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/CrearUsuarioExternoWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearUsuarioExternoWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/CrearUsuarioExternoWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CrearUsuarioExternoWSSoap,
            
            CrearUsuarioExternoWSSoap12,
        }
    }
}
