//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Mesas.Usuario
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", ConfigurationName="TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap")]
    public interface BusUsuarioWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/CrearUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.CrearUsuarioResponse1> CrearUsuarioAsync(TravelioSOAP.Mesas.Usuario.CrearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ingtegracion-bar-sinson-soap.runasp.net/ListarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.ListarUsuariosResponse> ListarUsuariosAsync(TravelioSOAP.Mesas.Usuario.ListarUsuariosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class CrearUsuarioResponse
    {
        
        private string mensajeField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class UsuarioItem
    {
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/")]
    public partial class UsuariosResponse
    {
        
        private UsuarioItem[] usuariosField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Usuario")]
        public UsuarioItem[] Usuarios
        {
            get
            {
                return this.usuariosField;
            }
            set
            {
                this.usuariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearUsuario", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class CrearUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=1)]
        public string apellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=2)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=3)]
        public string tipo_identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=4)]
        public string identificacion;
        
        public CrearUsuarioRequest()
        {
        }
        
        public CrearUsuarioRequest(string nombre, string apellido, string email, string tipo_identificacion, string identificacion)
        {
            this.nombre = nombre;
            this.apellido = apellido;
            this.email = email;
            this.tipo_identificacion = tipo_identificacion;
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearUsuarioResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class CrearUsuarioResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TravelioSOAP.Mesas.Usuario.CrearUsuarioResponse CrearUsuarioResult;
        
        public CrearUsuarioResponse1()
        {
        }
        
        public CrearUsuarioResponse1(TravelioSOAP.Mesas.Usuario.CrearUsuarioResponse CrearUsuarioResult)
        {
            this.CrearUsuarioResult = CrearUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarUsuarios", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class ListarUsuariosRequest
    {
        
        public ListarUsuariosRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarUsuariosResponse", WrapperNamespace="http://ingtegracion-bar-sinson-soap.runasp.net/", IsWrapped=true)]
    public partial class ListarUsuariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ingtegracion-bar-sinson-soap.runasp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TravelioSOAP.Mesas.Usuario.UsuariosResponse UsuariosResponse;
        
        public ListarUsuariosResponse()
        {
        }
        
        public ListarUsuariosResponse(TravelioSOAP.Mesas.Usuario.UsuariosResponse UsuariosResponse)
        {
            this.UsuariosResponse = UsuariosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface BusUsuarioWSSoapChannel : TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BusUsuarioWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap>, TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BusUsuarioWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BusUsuarioWSSoapClient.GetBindingForEndpoint(endpointConfiguration), BusUsuarioWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusUsuarioWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BusUsuarioWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusUsuarioWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BusUsuarioWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusUsuarioWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.CrearUsuarioResponse1> TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap.CrearUsuarioAsync(TravelioSOAP.Mesas.Usuario.CrearUsuarioRequest request)
        {
            return base.Channel.CrearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.CrearUsuarioResponse1> CrearUsuarioAsync(string nombre, string apellido, string email, string tipo_identificacion, string identificacion)
        {
            TravelioSOAP.Mesas.Usuario.CrearUsuarioRequest inValue = new TravelioSOAP.Mesas.Usuario.CrearUsuarioRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.email = email;
            inValue.tipo_identificacion = tipo_identificacion;
            inValue.identificacion = identificacion;
            return ((TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap)(this)).CrearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.ListarUsuariosResponse> TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap.ListarUsuariosAsync(TravelioSOAP.Mesas.Usuario.ListarUsuariosRequest request)
        {
            return base.Channel.ListarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Mesas.Usuario.ListarUsuariosResponse> ListarUsuariosAsync()
        {
            TravelioSOAP.Mesas.Usuario.ListarUsuariosRequest inValue = new TravelioSOAP.Mesas.Usuario.ListarUsuariosRequest();
            return ((TravelioSOAP.Mesas.Usuario.BusUsuarioWSSoap)(this)).ListarUsuariosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusUsuarioWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BusUsuarioWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BusUsuarioWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusUsuarioWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BusUsuarioWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dragonrojosoap.runasp.net/BusUsuarioWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BusUsuarioWSSoap,
            
            BusUsuarioWSSoap12,
        }
    }
}
