//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Habitaciones.ReservarHabitacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaConfirmadaDto", Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class ReservaConfirmadaDto : object
    {
        
        private int IdReservaField;
        
        private System.Nullable<decimal> CostoTotalReservaField;
        
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        private System.Nullable<System.DateTime> FechaInicioField;
        
        private System.Nullable<System.DateTime> FechaFinField;
        
        private string EstadoGeneralField;
        
        private System.Nullable<bool> EstadoField;
        
        private string NombreField;
        
        private string ApellidoField;
        
        private string CorreoField;
        
        private string TipoDocumentoField;
        
        private string HabitacionField;
        
        private System.Nullable<decimal> PrecioNormalField;
        
        private System.Nullable<decimal> PrecioActualField;
        
        private System.Nullable<int> CapacidadField;
        
        private object _linksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReserva
        {
            get
            {
                return this.IdReservaField;
            }
            set
            {
                this.IdReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<decimal> CostoTotalReserva
        {
            get
            {
                return this.CostoTotalReservaField;
            }
            set
            {
                this.CostoTotalReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EstadoGeneral
        {
            get
            {
                return this.EstadoGeneralField;
            }
            set
            {
                this.EstadoGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<bool> Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Habitacion
        {
            get
            {
                return this.HabitacionField;
            }
            set
            {
                this.HabitacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<decimal> PrecioNormal
        {
            get
            {
                return this.PrecioNormalField;
            }
            set
            {
                this.PrecioNormalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<decimal> PrecioActual
        {
            get
            {
                return this.PrecioActualField;
            }
            set
            {
                this.PrecioActualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public object _links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.hotelesoap.com/booking", ConfigurationName="TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap")]
    public interface ReservarHabitacionWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.hotelesoap.com/booking/reservarHabitacion", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionResponse> reservarHabitacionAsync(TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservarHabitacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservarHabitacion", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequestBody Body;
        
        public reservarHabitacionRequest()
        {
        }
        
        public reservarHabitacionRequest(TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class reservarHabitacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idHabitacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idHold;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string documento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime fechaFin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int numeroHuespedes;
        
        public reservarHabitacionRequestBody()
        {
        }
        
        public reservarHabitacionRequestBody(string idHabitacion, string idHold, string nombre, string apellido, string correo, string tipoDocumento, string documento, System.DateTime fechaInicio, System.DateTime fechaFin, int numeroHuespedes)
        {
            this.idHabitacion = idHabitacion;
            this.idHold = idHold;
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.tipoDocumento = tipoDocumento;
            this.documento = documento;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.numeroHuespedes = numeroHuespedes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservarHabitacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservarHabitacionResponse", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionResponseBody Body;
        
        public reservarHabitacionResponse()
        {
        }
        
        public reservarHabitacionResponse(TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class reservarHabitacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Habitaciones.ReservarHabitacion.ReservaConfirmadaDto reservarHabitacionResult;
        
        public reservarHabitacionResponseBody()
        {
        }
        
        public reservarHabitacionResponseBody(TravelioSOAP.Habitaciones.ReservarHabitacion.ReservaConfirmadaDto reservarHabitacionResult)
        {
            this.reservarHabitacionResult = reservarHabitacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ReservarHabitacionWSSoapChannel : TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ReservarHabitacionWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap>, TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReservarHabitacionWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ReservarHabitacionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), ReservarHabitacionWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservarHabitacionWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReservarHabitacionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservarHabitacionWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReservarHabitacionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservarHabitacionWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionResponse> TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap.reservarHabitacionAsync(TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequest request)
        {
            return base.Channel.reservarHabitacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionResponse> reservarHabitacionAsync(string idHabitacion, string idHold, string nombre, string apellido, string correo, string tipoDocumento, string documento, System.DateTime fechaInicio, System.DateTime fechaFin, int numeroHuespedes)
        {
            TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequest inValue = new TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequest();
            inValue.Body = new TravelioSOAP.Habitaciones.ReservarHabitacion.reservarHabitacionRequestBody();
            inValue.Body.idHabitacion = idHabitacion;
            inValue.Body.idHold = idHold;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.correo = correo;
            inValue.Body.tipoDocumento = tipoDocumento;
            inValue.Body.documento = documento;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            inValue.Body.numeroHuespedes = numeroHuespedes;
            return ((TravelioSOAP.Habitaciones.ReservarHabitacion.ReservarHabitacionWSSoap)(this)).reservarHabitacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReservarHabitacionWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ReservarHabitacionWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReservarHabitacionWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/ReservarHabitacionWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ReservarHabitacionWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/ReservarHabitacionWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ReservarHabitacionWSSoap,
            
            ReservarHabitacionWSSoap12,
        }
    }
}
