//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Busqueda
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoBookingDto", Namespace="http://rentaautos.ec/integracion")]
    public partial class AutoBookingDto : object
    {
        
        private string IdAutoField;
        
        private string TipoField;
        
        private int CapacidadField;
        
        private decimal PrecioNormalField;
        
        private System.Nullable<decimal> PrecioActualField;
        
        private string UriImagenField;
        
        private string CiudadField;
        
        private string PaisField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdAuto
        {
            get
            {
                return this.IdAutoField;
            }
            set
            {
                this.IdAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal PrecioNormal
        {
            get
            {
                return this.PrecioNormalField;
            }
            set
            {
                this.PrecioNormalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> PrecioActual
        {
            get
            {
                return this.PrecioActualField;
            }
            set
            {
                this.PrecioActualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UriImagen
        {
            get
            {
                return this.UriImagenField;
            }
            set
            {
                this.UriImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentaautos.ec/integracion", ConfigurationName="TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap")]
    public interface WS_BuscarAutosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentaautos.ec/integracion/buscarAutos", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Busqueda.buscarAutosResponse> buscarAutosAsync(TravelioSOAP.Autos.Busqueda.buscarAutosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarAutosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarAutos", Namespace="http://rentaautos.ec/integracion", Order=0)]
        public TravelioSOAP.Autos.Busqueda.buscarAutosRequestBody Body;
        
        public buscarAutosRequest()
        {
        }
        
        public buscarAutosRequest(TravelioSOAP.Autos.Busqueda.buscarAutosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/integracion")]
    public partial class buscarAutosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string transmision;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> capacidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> precio_min;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> precio_max;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pais;
        
        public buscarAutosRequestBody()
        {
        }
        
        public buscarAutosRequestBody(string categoria, string transmision, System.Nullable<int> capacidad, System.Nullable<decimal> precio_min, System.Nullable<decimal> precio_max, string sort, string ciudad, string pais)
        {
            this.categoria = categoria;
            this.transmision = transmision;
            this.capacidad = capacidad;
            this.precio_min = precio_min;
            this.precio_max = precio_max;
            this.sort = sort;
            this.ciudad = ciudad;
            this.pais = pais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarAutosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarAutosResponse", Namespace="http://rentaautos.ec/integracion", Order=0)]
        public TravelioSOAP.Autos.Busqueda.buscarAutosResponseBody Body;
        
        public buscarAutosResponse()
        {
        }
        
        public buscarAutosResponse(TravelioSOAP.Autos.Busqueda.buscarAutosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/integracion")]
    public partial class buscarAutosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Busqueda.AutoBookingDto[] buscarAutosResult;
        
        public buscarAutosResponseBody()
        {
        }
        
        public buscarAutosResponseBody(TravelioSOAP.Autos.Busqueda.AutoBookingDto[] buscarAutosResult)
        {
            this.buscarAutosResult = buscarAutosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_BuscarAutosSoapChannel : TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_BuscarAutosSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap>, TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_BuscarAutosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_BuscarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_BuscarAutosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_BuscarAutosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_BuscarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_BuscarAutosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_BuscarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_BuscarAutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Busqueda.buscarAutosResponse> TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap.buscarAutosAsync(TravelioSOAP.Autos.Busqueda.buscarAutosRequest request)
        {
            return base.Channel.buscarAutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Busqueda.buscarAutosResponse> buscarAutosAsync(string categoria, string transmision, System.Nullable<int> capacidad, System.Nullable<decimal> precio_min, System.Nullable<decimal> precio_max, string sort, string ciudad, string pais)
        {
            TravelioSOAP.Autos.Busqueda.buscarAutosRequest inValue = new TravelioSOAP.Autos.Busqueda.buscarAutosRequest();
            inValue.Body = new TravelioSOAP.Autos.Busqueda.buscarAutosRequestBody();
            inValue.Body.categoria = categoria;
            inValue.Body.transmision = transmision;
            inValue.Body.capacidad = capacidad;
            inValue.Body.precio_min = precio_min;
            inValue.Body.precio_max = precio_max;
            inValue.Body.sort = sort;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            return ((TravelioSOAP.Autos.Busqueda.WS_BuscarAutosSoap)(this)).buscarAutosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_BuscarAutosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_BuscarAutosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_BuscarAutosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_BuscarAutos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_BuscarAutosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_BuscarAutos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_BuscarAutosSoap,
            
            WS_BuscarAutosSoap12,
        }
    }
}
