//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Cliente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioExternoDto", Namespace="http://rentaautos.ec/gestion")]
    public partial class UsuarioExternoDto : object
    {
        
        private string NombreField;
        
        private string ApellidoField;
        
        private string EmailField;
        
        private string TelefonoField;
        
        private string PaisField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioProcesadoResponseDto", Namespace="http://rentaautos.ec/gestion")]
    public partial class UsuarioProcesadoResponseDto : object
    {
        
        private int IdUsuarioField;
        
        private string BookingUserIdField;
        
        private string NombreCompletoField;
        
        private string EmailField;
        
        private string TelefonoField;
        
        private string PaisField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookingUserId
        {
            get
            {
                return this.BookingUserIdField;
            }
            set
            {
                this.BookingUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentaautos.ec/gestion", ConfigurationName="TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap")]
    public interface WS_UsuarioExternoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentaautos.ec/gestion/ProcesarUsuarioExterno", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoResponse> ProcesarUsuarioExternoAsync(TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesarUsuarioExternoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesarUsuarioExterno", Namespace="http://rentaautos.ec/gestion", Order=0)]
        public TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequestBody Body;
        
        public ProcesarUsuarioExternoRequest()
        {
        }
        
        public ProcesarUsuarioExternoRequest(TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/gestion")]
    public partial class ProcesarUsuarioExternoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Cliente.UsuarioExternoDto nuevoUsuario;
        
        public ProcesarUsuarioExternoRequestBody()
        {
        }
        
        public ProcesarUsuarioExternoRequestBody(TravelioSOAP.Autos.Cliente.UsuarioExternoDto nuevoUsuario)
        {
            this.nuevoUsuario = nuevoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesarUsuarioExternoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesarUsuarioExternoResponse", Namespace="http://rentaautos.ec/gestion", Order=0)]
        public TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoResponseBody Body;
        
        public ProcesarUsuarioExternoResponse()
        {
        }
        
        public ProcesarUsuarioExternoResponse(TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/gestion")]
    public partial class ProcesarUsuarioExternoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Cliente.UsuarioProcesadoResponseDto ProcesarUsuarioExternoResult;
        
        public ProcesarUsuarioExternoResponseBody()
        {
        }
        
        public ProcesarUsuarioExternoResponseBody(TravelioSOAP.Autos.Cliente.UsuarioProcesadoResponseDto ProcesarUsuarioExternoResult)
        {
            this.ProcesarUsuarioExternoResult = ProcesarUsuarioExternoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_UsuarioExternoSoapChannel : TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_UsuarioExternoSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap>, TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_UsuarioExternoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_UsuarioExternoSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_UsuarioExternoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_UsuarioExternoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_UsuarioExternoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_UsuarioExternoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_UsuarioExternoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_UsuarioExternoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoResponse> TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap.ProcesarUsuarioExternoAsync(TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequest request)
        {
            return base.Channel.ProcesarUsuarioExternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoResponse> ProcesarUsuarioExternoAsync(TravelioSOAP.Autos.Cliente.UsuarioExternoDto nuevoUsuario)
        {
            TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequest inValue = new TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequest();
            inValue.Body = new TravelioSOAP.Autos.Cliente.ProcesarUsuarioExternoRequestBody();
            inValue.Body.nuevoUsuario = nuevoUsuario;
            return ((TravelioSOAP.Autos.Cliente.WS_UsuarioExternoSoap)(this)).ProcesarUsuarioExternoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_UsuarioExternoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_UsuarioExternoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_UsuarioExternoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_UsuarioExterno.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_UsuarioExternoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_UsuarioExterno.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_UsuarioExternoSoap,
            
            WS_UsuarioExternoSoap12,
        }
    }
}
