//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Disponibilidad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarDisponibilidadSoapResponse", Namespace="http://integracion.rentaautos.com/booking")]
    public partial class ValidarDisponibilidadSoapResponse : object
    {
        
        private int IdVehiculoField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private bool DisponibleField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVehiculo
        {
            get
            {
                return this.IdVehiculoField;
            }
            set
            {
                this.IdVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Disponible
        {
            get
            {
                return this.DisponibleField;
            }
            set
            {
                this.DisponibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.rentaautos.com/booking", ConfigurationName="TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap")]
    public interface WS_DisponibilidadAutosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.rentaautos.com/booking/validarDisponibilidadAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoResponse> validarDisponibilidadAutoAsync(TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDisponibilidadAutoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDisponibilidadAuto", Namespace="http://integracion.rentaautos.com/booking", Order=0)]
        public TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequestBody Body;
        
        public validarDisponibilidadAutoRequest()
        {
        }
        
        public validarDisponibilidadAutoRequest(TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com/booking")]
    public partial class validarDisponibilidadAutoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idVehiculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaFin;
        
        public validarDisponibilidadAutoRequestBody()
        {
        }
        
        public validarDisponibilidadAutoRequestBody(string idVehiculo, System.DateTime fechaInicio, System.DateTime fechaFin)
        {
            this.idVehiculo = idVehiculo;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDisponibilidadAutoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDisponibilidadAutoResponse", Namespace="http://integracion.rentaautos.com/booking", Order=0)]
        public TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoResponseBody Body;
        
        public validarDisponibilidadAutoResponse()
        {
        }
        
        public validarDisponibilidadAutoResponse(TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com/booking")]
    public partial class validarDisponibilidadAutoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Disponibilidad.ValidarDisponibilidadSoapResponse validarDisponibilidadAutoResult;
        
        public validarDisponibilidadAutoResponseBody()
        {
        }
        
        public validarDisponibilidadAutoResponseBody(TravelioSOAP.Autos.Disponibilidad.ValidarDisponibilidadSoapResponse validarDisponibilidadAutoResult)
        {
            this.validarDisponibilidadAutoResult = validarDisponibilidadAutoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_DisponibilidadAutosSoapChannel : TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_DisponibilidadAutosSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap>, TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_DisponibilidadAutosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_DisponibilidadAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_DisponibilidadAutosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_DisponibilidadAutosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_DisponibilidadAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_DisponibilidadAutosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_DisponibilidadAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_DisponibilidadAutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoResponse> TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap.validarDisponibilidadAutoAsync(TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequest request)
        {
            return base.Channel.validarDisponibilidadAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoResponse> validarDisponibilidadAutoAsync(string idVehiculo, System.DateTime fechaInicio, System.DateTime fechaFin)
        {
            TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequest inValue = new TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequest();
            inValue.Body = new TravelioSOAP.Autos.Disponibilidad.validarDisponibilidadAutoRequestBody();
            inValue.Body.idVehiculo = idVehiculo;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            return ((TravelioSOAP.Autos.Disponibilidad.WS_DisponibilidadAutosSoap)(this)).validarDisponibilidadAutoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_DisponibilidadAutosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_DisponibilidadAutosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_DisponibilidadAutosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_DisponibilidadAutos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_DisponibilidadAutosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_DisponibilidadAutos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_DisponibilidadAutosSoap,
            
            WS_DisponibilidadAutosSoap12,
        }
    }
}
