//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Habitaciones.ValidarDisponibilidad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisponibilidadResultDto", Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class DisponibilidadResultDto : object
    {
        
        private bool DisponibleField;
        
        private string MensajeField;
        
        private object _linksField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Disponible
        {
            get
            {
                return this.DisponibleField;
            }
            set
            {
                this.DisponibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object _links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.hotelesoap.com/booking", ConfigurationName="TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap")]
    public interface ValidarDisponibilidadWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.hotelesoap.com/booking/validarDisponibilidadHabitacion", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionResponse> validarDisponibilidadHabitacionAsync(TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDisponibilidadHabitacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDisponibilidadHabitacion", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequestBody Body;
        
        public validarDisponibilidadHabitacionRequest()
        {
        }
        
        public validarDisponibilidadHabitacionRequest(TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class validarDisponibilidadHabitacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idHabitacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaFin;
        
        public validarDisponibilidadHabitacionRequestBody()
        {
        }
        
        public validarDisponibilidadHabitacionRequestBody(string idHabitacion, System.DateTime fechaInicio, System.DateTime fechaFin)
        {
            this.idHabitacion = idHabitacion;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDisponibilidadHabitacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDisponibilidadHabitacionResponse", Namespace="http://integracion.hotelesoap.com/booking", Order=0)]
        public TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionResponseBody Body;
        
        public validarDisponibilidadHabitacionResponse()
        {
        }
        
        public validarDisponibilidadHabitacionResponse(TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.hotelesoap.com/booking")]
    public partial class validarDisponibilidadHabitacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Habitaciones.ValidarDisponibilidad.DisponibilidadResultDto validarDisponibilidadHabitacionResult;
        
        public validarDisponibilidadHabitacionResponseBody()
        {
        }
        
        public validarDisponibilidadHabitacionResponseBody(TravelioSOAP.Habitaciones.ValidarDisponibilidad.DisponibilidadResultDto validarDisponibilidadHabitacionResult)
        {
            this.validarDisponibilidadHabitacionResult = validarDisponibilidadHabitacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ValidarDisponibilidadWSSoapChannel : TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ValidarDisponibilidadWSSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap>, TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidarDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ValidarDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), ValidarDisponibilidadWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidarDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidarDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidarDisponibilidadWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidarDisponibilidadWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidarDisponibilidadWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionResponse> TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap.validarDisponibilidadHabitacionAsync(TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequest request)
        {
            return base.Channel.validarDisponibilidadHabitacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionResponse> validarDisponibilidadHabitacionAsync(string idHabitacion, System.DateTime fechaInicio, System.DateTime fechaFin)
        {
            TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequest inValue = new TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequest();
            inValue.Body = new TravelioSOAP.Habitaciones.ValidarDisponibilidad.validarDisponibilidadHabitacionRequestBody();
            inValue.Body.idHabitacion = idHabitacion;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            return ((TravelioSOAP.Habitaciones.ValidarDisponibilidad.ValidarDisponibilidadWSSoap)(this)).validarDisponibilidadHabitacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidarDisponibilidadWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidarDisponibilidadWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidarDisponibilidadWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/ValidarDisponibilidadWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidarDisponibilidadWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://aureacuen.runasp.net/ValidarDisponibilidadWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ValidarDisponibilidadWSSoap,
            
            ValidarDisponibilidadWSSoap12,
        }
    }
}
