//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Reserva
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaDto", Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class ReservaDto : object
    {
        
        private int IdReservaField;
        
        private string NombreUsuarioField;
        
        private int IdVehiculoField;
        
        private string VehiculoNombreField;
        
        private string NumeroMatriculaField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private decimal TotalField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReserva
        {
            get
            {
                return this.IdReservaField;
            }
            set
            {
                this.IdReservaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdVehiculo
        {
            get
            {
                return this.IdVehiculoField;
            }
            set
            {
                this.IdVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VehiculoNombre
        {
            get
            {
                return this.VehiculoNombreField;
            }
            set
            {
                this.VehiculoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NumeroMatricula
        {
            get
            {
                return this.NumeroMatriculaField;
            }
            set
            {
                this.NumeroMatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracion.rentaautos.com.ec/", ConfigurationName="TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap")]
    public interface WS_ReservarAutosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.rentaautos.com.ec/ReservarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.ReservarAutoResponse> ReservarAutoAsync(TravelioSOAP.Autos.Reserva.ReservarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integracion.rentaautos.com.ec/TestConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.TestConexionResponse> TestConexionAsync(TravelioSOAP.Autos.Reserva.TestConexionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarAutoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarAuto", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Reserva.ReservarAutoRequestBody Body;
        
        public ReservarAutoRequest()
        {
        }
        
        public ReservarAutoRequest(TravelioSOAP.Autos.Reserva.ReservarAutoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class ReservarAutoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_auto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_hold;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipo_identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime fecha_inicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime fecha_fin;
        
        public ReservarAutoRequestBody()
        {
        }
        
        public ReservarAutoRequestBody(string id_auto, string id_hold, string nombre, string apellido, string tipo_identificacion, string identificacion, string correo, System.DateTime fecha_inicio, System.DateTime fecha_fin)
        {
            this.id_auto = id_auto;
            this.id_hold = id_hold;
            this.nombre = nombre;
            this.apellido = apellido;
            this.tipo_identificacion = tipo_identificacion;
            this.identificacion = identificacion;
            this.correo = correo;
            this.fecha_inicio = fecha_inicio;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarAutoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarAutoResponse", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Reserva.ReservarAutoResponseBody Body;
        
        public ReservarAutoResponse()
        {
        }
        
        public ReservarAutoResponse(TravelioSOAP.Autos.Reserva.ReservarAutoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class ReservarAutoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Reserva.ReservaDto ReservarAutoResult;
        
        public ReservarAutoResponseBody()
        {
        }
        
        public ReservarAutoResponseBody(TravelioSOAP.Autos.Reserva.ReservaDto ReservarAutoResult)
        {
            this.ReservarAutoResult = ReservarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexion", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Reserva.TestConexionRequestBody Body;
        
        public TestConexionRequest()
        {
        }
        
        public TestConexionRequest(TravelioSOAP.Autos.Reserva.TestConexionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConexionRequestBody
    {
        
        public TestConexionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexionResponse", Namespace="http://integracion.rentaautos.com.ec/", Order=0)]
        public TravelioSOAP.Autos.Reserva.TestConexionResponseBody Body;
        
        public TestConexionResponse()
        {
        }
        
        public TestConexionResponse(TravelioSOAP.Autos.Reserva.TestConexionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://integracion.rentaautos.com.ec/")]
    public partial class TestConexionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConexionResult;
        
        public TestConexionResponseBody()
        {
        }
        
        public TestConexionResponseBody(string TestConexionResult)
        {
            this.TestConexionResult = TestConexionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_ReservarAutosSoapChannel : TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_ReservarAutosSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap>, TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_ReservarAutosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_ReservarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_ReservarAutosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_ReservarAutosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_ReservarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_ReservarAutosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_ReservarAutosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_ReservarAutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.ReservarAutoResponse> TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap.ReservarAutoAsync(TravelioSOAP.Autos.Reserva.ReservarAutoRequest request)
        {
            return base.Channel.ReservarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.ReservarAutoResponse> ReservarAutoAsync(string id_auto, string id_hold, string nombre, string apellido, string tipo_identificacion, string identificacion, string correo, System.DateTime fecha_inicio, System.DateTime fecha_fin)
        {
            TravelioSOAP.Autos.Reserva.ReservarAutoRequest inValue = new TravelioSOAP.Autos.Reserva.ReservarAutoRequest();
            inValue.Body = new TravelioSOAP.Autos.Reserva.ReservarAutoRequestBody();
            inValue.Body.id_auto = id_auto;
            inValue.Body.id_hold = id_hold;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.tipo_identificacion = tipo_identificacion;
            inValue.Body.identificacion = identificacion;
            inValue.Body.correo = correo;
            inValue.Body.fecha_inicio = fecha_inicio;
            inValue.Body.fecha_fin = fecha_fin;
            return ((TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap)(this)).ReservarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.TestConexionResponse> TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap.TestConexionAsync(TravelioSOAP.Autos.Reserva.TestConexionRequest request)
        {
            return base.Channel.TestConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Reserva.TestConexionResponse> TestConexionAsync()
        {
            TravelioSOAP.Autos.Reserva.TestConexionRequest inValue = new TravelioSOAP.Autos.Reserva.TestConexionRequest();
            inValue.Body = new TravelioSOAP.Autos.Reserva.TestConexionRequestBody();
            return ((TravelioSOAP.Autos.Reserva.WS_ReservarAutosSoap)(this)).TestConexionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_ReservarAutosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_ReservarAutosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_ReservarAutosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_ReservarAutos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_ReservarAutosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_ReservarAutos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_ReservarAutosSoap,
            
            WS_ReservarAutosSoap12,
        }
    }
}
